### PR TITLE
adding dockerfile and singularity recipes for containers

### PR DESCRIPTION
**Pull request by vsoch**
This pull request will add container recipes (Docker and Singularity, respectively) to instruct the user how to generate the trumpbot in a container. This is helpful in case the user doesn't want to install or develop on his/her host, or to preserve a (working) version of the model with a particular version of dependencies.
It's fairly common that as tensorflow (or any ML library) is developed, older models become less and less likely to work. Containers can help with that :)

The instructions for building and running are included in the README, and I've also pushed a container to Docker Hub for you to use more quickly:

```bash
$ docker run vanessa/trumpbot
```
This will hopefully help to make development or use easy! If you have a Docker account, you could provide the container as an automated build from the Dockerfile (I didn't add this to the README thinking you might).

Signed-off-by: Vanessa Sochat <vsochat@stanford.edu>

### CODE REVIEW

**Comment by wyattferguson** [comment]
Hey Vanessa, thats a really good idea, I never even thought to spin up a container for it. For little projects like this I just assume people will just use a virtualenv, and deal with it. But I should totally start including that with all my projects.

**Comment by vsoch** [comment]
Cool! Yeah please ping me if you ever want help with any container builds - this one was fairly simple but it does get more complicated sometimes. Enjoy! :)

**Comment by wyattferguson** [comment]
I most definitely will! I was thumbing through your work and it is amazingly cool. Thank you for taking the time for my little project.

**Comment by vsoch** [comment]
I found it on reddit - keep up the good work! The entire reason I wanted to be a software engineer is to have fun, so little things like this fit exactly with that :)

**Pull request merged**
